### PR TITLE
Fixed all open issues, overhauled views, updated dependencies and migrated code to swift 4.2

### PR DESCRIPTION
**Pull request by dotWee**
Important changes for the application:

1. Migrated source code to Swift 4.2
2. Updated window interface with complete set of constrains, introduced support for auto-layout and dark mode (macOS 10.14 only)
3. Updated cocoapods dependencies
4. Fixed issue #1 #2 and #3

### CODE REVIEW

**Comment by dotWee** [comment]
This should fix #2, as Alamofire introduced system-wide proxy support. Also #3 should be fixed through https://github.com/naman14/Muzei-macOS/pull/4/commits/5817857f4bbbb3d108af20d92234e65a6e0e37e5.

**Comment by dotWee** [comment]
5. Another maybe noteworthy change: Support for [Unsplash](https://unsplash.com/) as wallpaper source.

**Comment by naman14** [comment]
@dotWee Thanks for the PR, this looks quite good, let me test it and will then make a release after merging

**Comment by dotWee** [comment]
You may need to issue an Access Key for Unsplash first and append it to their API URL within the `UnsplashSource.swift` file to get everything work: https://github.com/naman14/Muzei-macOS/blob/4c29459fb3216ed749bea83fb73bb994d056bb2a/MuzeiOSX/ImageSources/UnsplashSource.swift#L16

Note: as of their developer guidelines, both Access Key and Secret Key must remain confidential. So don't commit it. ;)

**Comment by naman14** [comment]
Yeah, saw that, will create one for publishing a release but wouldn't commit

**Pull request merged**
